### ISSUE TITLE
AddLoginToUserViewModel.loadedCommandExecute: Error with converting DateTime

### ISSUE THREAD

**Issue by efilnukefesin** [efilnukefesin/PermissionServer#13]
Newtonsoft.Json.JsonReaderException: "Could not convert string to DateTime: 2019-07-01T14:51:0009180616+02:00. Path 'payload[0].submitTime', line 1, position 84."

https://stackoverflow.com/questions/21744067/jsonconvert-deserializeobject-could-not-convert-string-to-datetime-when-using-no

**Comment by efilnukefesin** [comment]
Datetime affected:
2019-07-01T14:51:0009180616+02:00

**Comment by efilnukefesin** [comment]
Possible solutions:
1) use individual DatetimeConverter when Serializing and Deserializing (everywhere, always)
2) add logic to classes using datetimes
3) try using datetimeoffset

**Comment by efilnukefesin** [comment]
Same result with 3):
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Nachricht = Could not convert string to DateTimeOffset: 2019-07-01T14:51:0009180616+02:00. Path 'payload[0].submitTime', line 1, position 84.
  Quelle = Newtonsoft.Json
  Stapelüberwachung:
   at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTimeOffset()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NET.efilnukefesin.Implementations.Services.DataService.RestDataService.RestDataService.<GetAllAsync>d__12`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PermissionServer.SDK.Client.<GetUnknownLoginsAsync>d__23.MoveNext() in D:\Programizing\C# Net Standard\PermissionServer\src\PermissionServer.SDK\Client.cs:line 253
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AdminApp.ViewModels.AddLoginToUserViewModel.<loadedCommandExecute>d__61.MoveNext() in D:\Programizing\C# Net Standard\PermissionServer\src\AdminApp\ViewModels\AddLoginToUserViewModel.cs:line 143

**Comment by efilnukefesin** [comment]
Possible solutions:

1) use individual DatetimeConverter when Serializing and Deserializing (everywhere, always)
2) add logic to classes using datetimes

**Comment by efilnukefesin** [comment]
Special question: why does it work in File Storage but not with Rest Storage?

**Comment by efilnukefesin** [comment]
Testable in c9210df9

**Comment by efilnukefesin** [comment]
Special question: why does this work in File Storage?!?

**Comment by efilnukefesin** [comment]
fixed with 980f6b67 - used option #2 with InvariantCulture.
