### ISSUE TITLE
AddLoginToUserView: Error when selecting Login by Click

### ISSUE THREAD

**Issue by efilnukefesin** [efilnukefesin/PermissionServer#14]
System.Windows.Data Error: 23 : Cannot convert 'PermissionServer.Models.UnknownLogin' from type 'UnknownLogin' to type 'PermissionServer.Models.Login' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: TypeConverter cannot convert from PermissionServer.Models.UnknownLogin.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
System.Windows.Data Error: 7 : ConvertBack cannot convert value 'PermissionServer.Models.UnknownLogin' (type 'UnknownLogin'). BindingExpression:Path=SelectedLogin; DataItem='AddLoginToUserViewModel' (HashCode=20764673); target element is 'ListView' (Name=''); target property is 'SelectedItem' (type 'Object') NotSupportedException:'System.NotSupportedException: TypeConverter cannot convert from PermissionServer.Models.UnknownLogin.
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.ObjectTargetConverter.ConvertBack(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertBackHelper(IValueConverter converter, Object value, Type sourceType, Object parameter, CultureInfo culture)'

**Comment by efilnukefesin** [comment]
![image](https://user-images.githubusercontent.com/1336240/60466043-dec1b980-9c52-11e9-8ec1-6edeeb56c064.png)
plus the ListView is being colored RED

**Comment by efilnukefesin** [comment]
solved with 377a7415 - wrong binding target
